import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Link from 'next/link';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function Navigation() {
  return (
    <nav className="p-4 bg-white shadow">
      <div className="container mx-auto flex flex-wrap gap-x-4 gap-y-1">
        <Link href="/" className="hover:underline">
          Original Visualization
        </Link>
        <Link href="/comparison" className="hover:underline">
          Method Comparison
        </Link>
        <Link href="/detailed" className="hover:underline">
          Detailed Analysis
        </Link>
        <Link href="/distortion" className="hover:underline">
          Distortion Map
        </Link>
        <Link href="/paradoxes" className="hover:underline">
          Voting Paradoxes
        </Link>
      </div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
